<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * First version of the quiz model
 */
class Version20170911195928 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE phpugh_quiz_domain_model_result (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpugh_quiz_domain_model_category (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpugh_quiz_domain_model_quiz (persistence_object_identifier VARCHAR(40) NOT NULL, category VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, INDEX IDX_925EAFA564C19C1 (category), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpugh_quiz_domain_model_answer (persistence_object_identifier VARCHAR(40) NOT NULL, question VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, correct TINYINT(1) NOT NULL, INDEX IDX_51DB7926B6F7494E (question), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpugh_quiz_domain_model_question (persistence_object_identifier VARCHAR(40) NOT NULL, quiz VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, INDEX IDX_220AF09DA412FA92 (quiz), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_quiz ADD CONSTRAINT FK_925EAFA564C19C1 FOREIGN KEY (category) REFERENCES phpugh_quiz_domain_model_category (persistence_object_identifier)');
        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_answer ADD CONSTRAINT FK_51DB7926B6F7494E FOREIGN KEY (question) REFERENCES phpugh_quiz_domain_model_question (persistence_object_identifier)');
        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_question ADD CONSTRAINT FK_220AF09DA412FA92 FOREIGN KEY (quiz) REFERENCES phpugh_quiz_domain_model_quiz (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_quiz DROP FOREIGN KEY FK_925EAFA564C19C1');
        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_question DROP FOREIGN KEY FK_220AF09DA412FA92');
        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_answer DROP FOREIGN KEY FK_51DB7926B6F7494E');
        $this->addSql('DROP TABLE phpugh_quiz_domain_model_result');
        $this->addSql('DROP TABLE phpugh_quiz_domain_model_category');
        $this->addSql('DROP TABLE phpugh_quiz_domain_model_quiz');
        $this->addSql('DROP TABLE phpugh_quiz_domain_model_answer');
        $this->addSql('DROP TABLE phpugh_quiz_domain_model_question');
    }
}