<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20171009191559 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_answer CHANGE question question VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_question CHANGE quiz quiz VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_quiz CHANGE category category VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_result ADD quiz VARCHAR(40) DEFAULT NULL, ADD player VARCHAR(255) NOT NULL, ADD correctanswers INT NOT NULL');
        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_result ADD CONSTRAINT FK_986CF210A412FA92 FOREIGN KEY (quiz) REFERENCES phpugh_quiz_domain_model_quiz (persistence_object_identifier)');
        $this->addSql('CREATE INDEX IDX_986CF210A412FA92 ON phpugh_quiz_domain_model_result (quiz)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE neos_flow_security_account CHANGE credentialssource credentialssource VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE expirationdate expirationdate DATETIME DEFAULT \'NULL\', CHANGE lastsuccessfulauthenticationdate lastsuccessfulauthenticationdate DATETIME DEFAULT \'NULL\', CHANGE failedauthenticationcount failedauthenticationcount INT DEFAULT NULL, CHANGE roleidentifiers roleidentifiers LONGTEXT DEFAULT \'NULL\' COLLATE utf8_unicode_ci COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_answer CHANGE question question VARCHAR(40) DEFAULT \'NULL\' COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_question CHANGE quiz quiz VARCHAR(40) DEFAULT \'NULL\' COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_quiz CHANGE category category VARCHAR(40) DEFAULT \'NULL\' COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_result DROP FOREIGN KEY FK_986CF210A412FA92');
        $this->addSql('DROP INDEX IDX_986CF210A412FA92 ON phpugh_quiz_domain_model_result');
        $this->addSql('ALTER TABLE phpugh_quiz_domain_model_result DROP quiz, DROP player, DROP correctanswers');
    }
}